version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: monthly
