name: ci

on:
  push:
    branches: [ main, main-local, local-test ]
  pull_request:
    branches: [ main, main-local ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
        cache: true

    - name: Build
      run: |
        set -xue
        go install golang.org/x/tools/cmd/goyacc@latest
        go get .
        go generate ./...
        go build .

    - name: staticcheck
      continue-on-error: true
      uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2022.1.3"
        install-go: false

    - name: golangci-lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@v4
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.50.1

    - name: Test
      run: go test ./...

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: tests/testout.html
