name: ci

on:
  push:
    branches: [ main, main-local, local-test ]
  pull_request:
    branches: [ main, main-local ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: |
          set -xue
          go install golang.org/x/tools/cmd/goyacc@latest
          go get .
          go generate ./...
          go build .
      - name: Test
        run: |
          cd tests
          ./runtests.sh
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: tests/testout.html